BoardGamesShop/Areas/Admin/Controllers/CompanyController.cs
using BoardGames.DataAccess;
using BoardGames.DataAccess.Repository.IRepository;
using BoardGames.Models;
using BoardGames.Models.ViewModels;
using BoardGamesShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BoardGamesShop.Controllers
{[Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _db;




        public CompanyController(IUnitOfWork db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        
        //GET
        public IActionResult Upsert(int? id)
        {
            Company company = new()

;
            if (id == null || id == 0)
            {
                //create
                return View(company);
                
            }
            else
            {
                //update
                company = _db.Company.GetFirstOrDefault(u => u.Id == id);
                return View(company);

            }
           


        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company obj)
        {
            if (ModelState.IsValid)
            {
                
                if(obj.Id == 0)
                {
                    _db.Company.Add(obj);
                    TempData["success"] = "Firma dodana pomyślnie";
                }
                else
                {
                    _db.Company.Update(obj);
                    TempData["success"] = "Firma edytowana pomyślnie";
                }
                
                _db.Save();
                
                return RedirectToAction("Index");

            }
            return View(obj);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var companyList = _db.Company.GetAll();
            return Json(new { data = companyList });
        }
        //POST
        [HttpDelete]
     
        public IActionResult Delete(int? id)
        {
            var obj = _db.Company.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {

                return Json(new {success = false, message ="Error"});

            }
            

            _db.Company.Remove(obj);
            _db.Save();
           
            return Json(new { success = true, message = "Usunięto pomyślnie" });


        }
        #endregion
    }

}

BoardGamesShop/Areas/Admin/Controllers/GameController.cs
using BoardGames.DataAccess;
using BoardGames.DataAccess.Repository.IRepository;
using BoardGames.Models;
using BoardGames.Models.ViewModels;
using BoardGamesShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BoardGamesShop.Controllers
{[Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class GameController : Controller
    {
        private readonly IUnitOfWork _db;
        private readonly IWebHostEnvironment _hostEnviroment;



        public GameController(IUnitOfWork db, IWebHostEnvironment hostEnvironment)
        {
            _db = db;
            _hostEnviroment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        
        //GET
        public IActionResult Upsert(int? id)
        {
            GameVM gameVM = new()
            {
                Game = new(),
                CategoryList = _db.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
            }
;
            if (id == null || id == 0)
            {
                //create
                return View(gameVM);
                
            }
            else
            {
                //update
                gameVM.Game = _db.Game.GetFirstOrDefault(u => u.Id == id);
                return View(gameVM);

            }
           


        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(GameVM obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnviroment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"img\gamesImg");
                    var extension = Path.GetExtension(file.FileName);
                    if (obj.Game.ImageUrl != null)
                    {
                        var oldImgPath = Path.Combine(wwwRootPath,obj.Game.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImgPath))
                        {
                            System.IO.File.Delete(oldImgPath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads,fileName+ extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.Game.ImageUrl = @"\img\gamesImg\" + fileName + extension;
                }
                if(obj.Game.Id == 0)
                {
                    _db.Game.Add(obj.Game);
                }
                else
                {
                    _db.Game.Update(obj.Game);
                }
                
                _db.Save();
                TempData["success"] = "Gra dodana pomyślnie";
                return RedirectToAction("Index");

            }
            return View(obj);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var gameList = _db.Game.GetAll(includeProperties:"Category");
            return Json(new { data = gameList });
        }
        //POST
        [HttpDelete]
     
        public IActionResult Delete(int? id)
        {
            var obj = _db.Game.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {

                return Json(new {success = false, message ="Error"});

            }
            var oldImgPath = Path.Combine(_hostEnviroment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImgPath))
            {
                System.IO.File.Delete(oldImgPath);
            }

            _db.Game.Remove(obj);
            _db.Save();
           
            return Json(new { success = true, message = "Usunięto pomyślnie" });


        }
        #endregion
    }

}

BoardGamesShop/Areas/Customer/Controllers/ShoppingCartController.cs
using BoardGames.DataAccess.Repository.IRepository;
using BoardGames.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BoardGamesShop.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IUnitOfWork _unitofWork;
        public ShoppingCartVM ShoppingCartVM { get; set; }
        public ShoppingCartController( IUnitOfWork unitOfWork)
        {
           
            _unitofWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ShoppingCartVM = new ShoppingCartVM() 
            { 
                ListCart = _unitofWork.ShoppingCart.GetAll(u=>u.ApplicationUserId==claim.Value, includeProperties: "Game")
            };
            foreach(var item in ShoppingCartVM.ListCart)
            {
                item.Price = GetPrice(item.Count, item.Game.Price, item.Game.Price3, item.Game.Price10);
                ShoppingCartVM.CartTotal +=(item.Price * item.Count);
            }
            return View(ShoppingCartVM);
        }
        public IActionResult Plus(int cartId)
        {
            var cart = _unitofWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
            _unitofWork.ShoppingCart.IncrementCount(cart, 1);
            _unitofWork.Save();
            return RedirectToAction("Index");
        }
        public IActionResult Minus(int cartId)
        {
            var cart = _unitofWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
            if(cart.Count <= 1)
            {
                _unitofWork.ShoppingCart.Remove(cart);
            }
            else
            {
            _unitofWork.ShoppingCart.DecrementCount(cart, 1);
            }

            _unitofWork.Save();
            return RedirectToAction("Index");
        }
        public IActionResult Remove(int cartId)
        {
            var cart = _unitofWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
            _unitofWork.ShoppingCart.Remove(cart);
            _unitofWork.Save();
            return RedirectToAction("Index");
        }
        private double GetPrice(double quantity, double price, double price3, double price10)
        {
            if (quantity <= 3)
            {
                return price;
            }
            else
            {
                if(quantity<=10)
                {
                    return price3;
                }
                return price10;
            }
        }

    }
}

BoardGamesShop/Controllers/CategoryController.cs
using BoardGames.DataAccess;
using BoardGames.DataAccess.Repository.IRepository;
using BoardGames.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoardGamesShop.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _db;



        public CategoryController(IUnitOfWork db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //Return a list to the view
            IEnumerable<Category> categoryList = _db.Category.GetAll();

            return View(categoryList);
        }
        //GET
        public IActionResult Create()
        {

            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if(obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Nazwa kategorii nie może być taka sama jak kolejność wyświetlania.");
            }
            if (ModelState.IsValid)
            {            
                _db.Category.Add(obj);
                _db.Save();
                TempData["success"] = "Kategoria utworzona pomyślnie";
                return RedirectToAction("Index");

            }
            return View(obj);
        }
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var catFromDb = _db.Category.GetFirstOrDefault(u=>u.Id==id);
            if (catFromDb == null)
            {

                return NotFound();

            }
            return View(catFromDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Nazwa kategorii nie może być taka sama jak kolejność wyświetlania.");
            }
            if (ModelState.IsValid)
            {
                _db.Category.Update(obj);
                _db.Save();
                TempData["success"] = "Kategoria edytowana pomyślnie";
                return RedirectToAction("Index");

            }
            return View(obj);
        }
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var catFromDb = _db.Category.GetFirstOrDefault(u => u.Id == id);
            if (catFromDb == null)
            {

                return NotFound();

            }
            return View(catFromDb);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var catFromDb = _db.Category.GetFirstOrDefault(u => u.Id == id);
            if (catFromDb == null)
            {

                return NotFound();

            }


            _db.Category.Remove(catFromDb);
            _db.Save();
            TempData["success"] = "Kategoria usunięta pomyślnie";
            return RedirectToAction("Index");

            
            
        }
    }
}

BoardGamesShop/Views/Shared/_Layout.cshtml
@using BoardGamesShop.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoardGamesShop</title>
    <link rel="stylesheet" href="~/css/bootswatchMintyTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BoardGamesShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  `     <div class="container-fluid">
           <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BoardGamesShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
        </button>

      <div class="navbar-collapse collapse show" id="navbarColor01" style="">
      <ul class="navbar-nav me-auto">
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                              <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Kategorie</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" asp-area="Admin" asp-controller="Game" asp-action="Index">Gry Planszowe</a>
                            </li>
                             <li class="nav-item">
                              <a class="nav-link" asp-area="Admin" asp-controller="Company" asp-action="Index">Firmy</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">Dodaj użytkownika</a>
                            </li>
                        }

         <li class="nav-item">
          <a class="nav-link" asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index"><i class="bi bi-cart3"></i></a>
        </li>
      </ul>
      <partial name ="_LoginPartial"/>
    </div>
  </div>
</nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name = "_Notification"/>
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BoardGamesShop/Views/Shared/_Notification.cshtml
@if(TempData["success"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type= "text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if(TempData["error"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type= "text/javascript">
        toastr.success('@TempData["error"]');
    </script>
}